### ISSUE TITLE
How to debug connection issues

### ISSUE THREAD

**Issue by shivanshpatel35** [youliangtan/agentlace#5]
Hi,
I am making a client using the following code
```
    client = TrainerClient(
        "actor_env",
        FLAGS.ip,
        make_trainer_config(),
        data_store,
        wait_for_server=True,
    )
```

But I am stuck waiting for server
```
W0314 20:27:43.566129 140532221165952 trainer.py:178] Failed to connect to server, retrying...
W0314 20:27:46.370609 140532221165952 req_rep.py:130] Failed to send message: Resource temporarily unavailable
```

How can I debug this problem?

**Comment by youliangtan** [comment]
I don't have enough information to debug this. 

Did you run the server? Are both Server and Client sharing the same [TrainerConfig](https://github.com/youliangtan/agentlace/blob/e61032fbce8a1e6d3dc2aeba21de082e4bf46fe3/agentlace/trainer.py#L24-L35)? Is the ip address used by the server ping-able by the client terminal?

**Comment by shivanshpatel35** [comment]
I am running [SERL](https://serl-robot.github.io/), but modified it to work for XArm robot. I am posting in agentlace and not SERL repo because I though it was more relevant here.
I am trying to replicate the [peg insertion task](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py). The learner (policy) is a [TrainerServer](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py#L230) and the actor is a [TrainerClient](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py#L136).

Both are using the same trainer config builder [[1](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py#L139), [2](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py#L230)], which is making config [here](https://github.com/rail-berkeley/serl/blob/main/serl_launcher/serl_launcher/utils/launcher.py#L165). My IP is set to 'localhost'. I am able to ping from actor (TrainerClient) terminal to learner (TrainerServer) by running `ping localhost`.

**Comment by youliangtan** [comment]
Thanks for trying out SERL. Would check if the port is working too

Also just a sanity check, i would run the script below to make sure the trainer and client is working fine.
```py
from agentlace.trainer import TrainerServer, TrainerClient, TrainerConfig
from agentlace.data.data_store import QueuedDataStore

config = TrainerConfig(port_number=5488,broadcast_port=5489)

# start server
server = TrainerServer(config)
server.start(threaded=True)
server.register_data_store(
        "actor_env", QueuedDataStore(capacity=5))

# start client
client = TrainerClient(
        "actor_env",
        "localhost",
        config,
        QueuedDataStore(capacity=5),
        wait_for_server=True,
)

print("all passed")
```

**Comment by shivanshpatel35** [comment]
To check the port, I ran `netstat -tuln`. Two of its output rows are as follows:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
TCP             0           0     0.0.0.0:5489                         0.0.0.0:*        LISTEN     
TCP             0           0     0.0.0.0:5488                         0.0.0.0:*        LISTEN     
```
It looks like the ports are working.

Also, the script that you sent works, it printed "all passed".

**Comment by youliangtan** [comment]
Hmm, then this seems to be a different issue not related to agentlace. Feel free to open an issue on https://github.com/rail-berkeley/serl and add the printout logs from the `learner` and `actor` processes. Thanks
