### ISSUE TITLE
Adding a separate client-server connection for different components

### ISSUE THREAD

**Issue by gautams3** [youliangtan/agentlace#6]
I want to collect some of the env observations during RL at a different frequency compared to the actor. I plan to make it a separate process that connects to the actor via Agentlace and zmq, and passes in the latest observation (not a previously queued up obs). I am using the `TrainerServer` and `TrainerClient` setup from SERL, such as [in this file](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py).

What is the recommended way to achieve this? Is it best to use `ActionServer` as an `EnvServer`? Should this be on top of the `TrainerClient` that's already in the actor?

**Comment by youliangtan** [comment]
Hi @gautams3 

if i understand correctly, you would like to send custom data from the client (actor) --> server (learner) besides using the queued datastore/replaybuffer. In this case, you can use this [client.request()](https://github.com/youliangtan/agentlace/blob/e61032fbce8a1e6d3dc2aeba21de082e4bf46fe3/agentlace/trainer.py#L229) from the actor, and a [request_callback](https://github.com/youliangtan/agentlace/blob/e61032fbce8a1e6d3dc2aeba21de082e4bf46fe3/agentlace/trainer.py#L68C1-L69C1) fn from the server to receive the msg.

Let me know if this works

**Comment by youliangtan** [comment]
This can be implemented as a separate thread, periodic callback timer etc, then use the `request()` api to send the data to the learner node.
